### ISSUE TITLE
Add clientId to mqtt initialization

### ISSUE THREAD

**Issue by zeridon** [bitfocus/companion-module-generic-mqtt#10]
In my personal mqtt setup (not using companion yet but just looking) i do require clientId's to be set otherwise no connection will happen.

Client ID's provide a method for access control and information for the admin of the mqtt server. As such Please implement clientId when opening a connection to the mqtt broker

https://github.com/bitfocus/companion-module-generic-mqtt/blob/d0744e473b79ade02bc4484d6d701db76b97a85e/index.js#L314

According to mqtt.js docs should be a simple job. Suggested value `bitfocus-companion-mqtt-<some-stable-id>`

**Comment by Julusian** [comment]
Thanks, I have rebased and merged the PR for this onto the overhaul for companion 3.0, so expect it to be available once 3.0 hits beta
