### ISSUE TITLE
MQTT client not disconnecting

### ISSUE THREAD

**Issue by estilles** [bitfocus/companion-module-generic-mqtt#13]
Issue reported by João Lima (@Boguinhos) via Slack

MQTT client not disconnecting from broker on:
- reconfig/reconnect
- instance removal/destroy

Was able to reproduce. Submitting fix.

**Comment by Julusian** [comment]
Thanks, I have rebased and merged the PR for this onto the overhaul for companion 3.0, so expect it to be available once 3.0 hits beta
