### ISSUE TITLE
Parsing variables to publish as topics

### ISSUE THREAD

**Issue by philipcain** [bitfocus/companion-module-generic-mqtt#18]
The `payload` field in the `Publish Message` action doesn't support parsing variables.

This would be a really valuable addition - the ability to push existing data from Companion to the MQTT broker. As the module currently stands, it seems like the only possible payload is manually entered text.

It was suggested in Slack that simply adding variable parsing to the `payload` in the existing Publish action might be a breaking change, if perhaps someone is pushing actual variable names as payloads rather than the variable values. If that's the case, maybe a new action could be added - `Publish Message from Variable`

**Comment by thargunitoth75** [comment]
I have the same problem.

**Comment by josephdadams** [comment]
it has this feature as of v2.0.2 of the module
