### ISSUE TITLE
Port number is not used in connection

### ISSUE THREAD

**Issue by EvanC-Au** [bitfocus/companion-module-generic-mqtt#5]
mqtt.connect (line 357 of index.js) currently utilises only the protocol, IP, and credentials, meaning that the port number in the config is ignored. As a result it will only connect on the default port for the protocol.

Maybe something like this would work?
```
var port = ""
if (self.config.port) {port = ":" + self.config.port}
self.mqttClient = mqtt.connect(self.config.protocol + self.config.broker_ip + port, {
	username: self.config.user,
	password: self.config.password
});
```
Edit: formatting

**Comment by Flyor** [comment]
I also got this problem. The Issue is about more than 1 year, could someone fix it please? @Julusian @oblogic7 @JeffreyDavidsz @krocheck
